// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod myelon {

#[allow(unused_imports, dead_code)]
pub mod ipc {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_SEQUENCE_STATUS: i8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_SEQUENCE_STATUS: i8 = 5;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_SEQUENCE_STATUS: [SequenceStatus; 6] = [
  SequenceStatus::Waiting,
  SequenceStatus::Running,
  SequenceStatus::Finished,
  SequenceStatus::Cached,
  SequenceStatus::Swapped,
  SequenceStatus::FinishSwapped,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct SequenceStatus(pub i8);
#[allow(non_upper_case_globals)]
impl SequenceStatus {
  pub const Waiting: Self = Self(0);
  pub const Running: Self = Self(1);
  pub const Finished: Self = Self(2);
  pub const Cached: Self = Self(3);
  pub const Swapped: Self = Self(4);
  pub const FinishSwapped: Self = Self(5);

  pub const ENUM_MIN: i8 = 0;
  pub const ENUM_MAX: i8 = 5;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Waiting,
    Self::Running,
    Self::Finished,
    Self::Cached,
    Self::Swapped,
    Self::FinishSwapped,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Waiting => Some("Waiting"),
      Self::Running => Some("Running"),
      Self::Finished => Some("Finished"),
      Self::Cached => Some("Cached"),
      Self::Swapped => Some("Swapped"),
      Self::FinishSwapped => Some("FinishSwapped"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for SequenceStatus {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for SequenceStatus {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<i8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for SequenceStatus {
    type Output = SequenceStatus;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<i8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for SequenceStatus {
  type Scalar = i8;
  #[inline]
  fn to_little_endian(self) -> i8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: i8) -> Self {
    let b = i8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for SequenceStatus {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    i8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for SequenceStatus {}
pub enum SamplingParamsOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SamplingParams<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SamplingParams<'a> {
  type Inner = SamplingParams<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SamplingParams<'a> {
  pub const VT_TEMPERATURE: ::flatbuffers::VOffsetT = 4;
  pub const VT_HAS_TEMPERATURE: ::flatbuffers::VOffsetT = 6;
  pub const VT_MAX_TOKENS: ::flatbuffers::VOffsetT = 8;
  pub const VT_HAS_MAX_TOKENS: ::flatbuffers::VOffsetT = 10;
  pub const VT_IGNORE_EOS: ::flatbuffers::VOffsetT = 12;
  pub const VT_TOP_K: ::flatbuffers::VOffsetT = 14;
  pub const VT_HAS_TOP_K: ::flatbuffers::VOffsetT = 16;
  pub const VT_TOP_P: ::flatbuffers::VOffsetT = 18;
  pub const VT_HAS_TOP_P: ::flatbuffers::VOffsetT = 20;
  pub const VT_SESSION_ID: ::flatbuffers::VOffsetT = 22;
  pub const VT_FREQUENCY_PENALTY: ::flatbuffers::VOffsetT = 24;
  pub const VT_HAS_FREQUENCY_PENALTY: ::flatbuffers::VOffsetT = 26;
  pub const VT_PRESENCE_PENALTY: ::flatbuffers::VOffsetT = 28;
  pub const VT_HAS_PRESENCE_PENALTY: ::flatbuffers::VOffsetT = 30;
  pub const VT_STOP_SEQUENCES: ::flatbuffers::VOffsetT = 32;
  pub const VT_THINKING: ::flatbuffers::VOffsetT = 34;
  pub const VT_HAS_THINKING: ::flatbuffers::VOffsetT = 36;
  pub const VT_MCP_MODE: ::flatbuffers::VOffsetT = 38;
  pub const VT_HAS_MCP_MODE: ::flatbuffers::VOffsetT = 40;
  pub const VT_GRAMMAR_JSON: ::flatbuffers::VOffsetT = 42;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SamplingParams { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SamplingParamsArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SamplingParams<'bldr>> {
    let mut builder = SamplingParamsBuilder::new(_fbb);
    builder.add_top_k(args.top_k);
    builder.add_max_tokens(args.max_tokens);
    if let Some(x) = args.grammar_json { builder.add_grammar_json(x); }
    if let Some(x) = args.stop_sequences { builder.add_stop_sequences(x); }
    builder.add_presence_penalty(args.presence_penalty);
    builder.add_frequency_penalty(args.frequency_penalty);
    if let Some(x) = args.session_id { builder.add_session_id(x); }
    builder.add_top_p(args.top_p);
    builder.add_temperature(args.temperature);
    builder.add_has_mcp_mode(args.has_mcp_mode);
    builder.add_mcp_mode(args.mcp_mode);
    builder.add_has_thinking(args.has_thinking);
    builder.add_thinking(args.thinking);
    builder.add_has_presence_penalty(args.has_presence_penalty);
    builder.add_has_frequency_penalty(args.has_frequency_penalty);
    builder.add_has_top_p(args.has_top_p);
    builder.add_has_top_k(args.has_top_k);
    builder.add_ignore_eos(args.ignore_eos);
    builder.add_has_max_tokens(args.has_max_tokens);
    builder.add_has_temperature(args.has_temperature);
    builder.finish()
  }


  #[inline]
  pub fn temperature(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SamplingParams::VT_TEMPERATURE, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn has_temperature(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_TEMPERATURE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn max_tokens(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SamplingParams::VT_MAX_TOKENS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_max_tokens(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_MAX_TOKENS, Some(false)).unwrap()}
  }
  #[inline]
  pub fn ignore_eos(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_IGNORE_EOS, Some(false)).unwrap()}
  }
  #[inline]
  pub fn top_k(&self) -> i64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i64>(SamplingParams::VT_TOP_K, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_top_k(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_TOP_K, Some(false)).unwrap()}
  }
  #[inline]
  pub fn top_p(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SamplingParams::VT_TOP_P, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn has_top_p(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_TOP_P, Some(false)).unwrap()}
  }
  #[inline]
  pub fn session_id(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SamplingParams::VT_SESSION_ID, None)}
  }
  #[inline]
  pub fn frequency_penalty(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SamplingParams::VT_FREQUENCY_PENALTY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn has_frequency_penalty(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_FREQUENCY_PENALTY, Some(false)).unwrap()}
  }
  #[inline]
  pub fn presence_penalty(&self) -> f32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<f32>(SamplingParams::VT_PRESENCE_PENALTY, Some(0.0)).unwrap()}
  }
  #[inline]
  pub fn has_presence_penalty(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_PRESENCE_PENALTY, Some(false)).unwrap()}
  }
  #[inline]
  pub fn stop_sequences(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>(SamplingParams::VT_STOP_SEQUENCES, None)}
  }
  #[inline]
  pub fn thinking(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_THINKING, Some(false)).unwrap()}
  }
  #[inline]
  pub fn has_thinking(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_THINKING, Some(false)).unwrap()}
  }
  #[inline]
  pub fn mcp_mode(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_MCP_MODE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn has_mcp_mode(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SamplingParams::VT_HAS_MCP_MODE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn grammar_json(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(SamplingParams::VT_GRAMMAR_JSON, None)}
  }
}

impl ::flatbuffers::Verifiable for SamplingParams<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<f32>("temperature", Self::VT_TEMPERATURE, false)?
     .visit_field::<bool>("has_temperature", Self::VT_HAS_TEMPERATURE, false)?
     .visit_field::<u64>("max_tokens", Self::VT_MAX_TOKENS, false)?
     .visit_field::<bool>("has_max_tokens", Self::VT_HAS_MAX_TOKENS, false)?
     .visit_field::<bool>("ignore_eos", Self::VT_IGNORE_EOS, false)?
     .visit_field::<i64>("top_k", Self::VT_TOP_K, false)?
     .visit_field::<bool>("has_top_k", Self::VT_HAS_TOP_K, false)?
     .visit_field::<f32>("top_p", Self::VT_TOP_P, false)?
     .visit_field::<bool>("has_top_p", Self::VT_HAS_TOP_P, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("session_id", Self::VT_SESSION_ID, false)?
     .visit_field::<f32>("frequency_penalty", Self::VT_FREQUENCY_PENALTY, false)?
     .visit_field::<bool>("has_frequency_penalty", Self::VT_HAS_FREQUENCY_PENALTY, false)?
     .visit_field::<f32>("presence_penalty", Self::VT_PRESENCE_PENALTY, false)?
     .visit_field::<bool>("has_presence_penalty", Self::VT_HAS_PRESENCE_PENALTY, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<&'_ str>>>>("stop_sequences", Self::VT_STOP_SEQUENCES, false)?
     .visit_field::<bool>("thinking", Self::VT_THINKING, false)?
     .visit_field::<bool>("has_thinking", Self::VT_HAS_THINKING, false)?
     .visit_field::<bool>("mcp_mode", Self::VT_MCP_MODE, false)?
     .visit_field::<bool>("has_mcp_mode", Self::VT_HAS_MCP_MODE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("grammar_json", Self::VT_GRAMMAR_JSON, false)?
     .finish();
    Ok(())
  }
}
pub struct SamplingParamsArgs<'a> {
    pub temperature: f32,
    pub has_temperature: bool,
    pub max_tokens: u64,
    pub has_max_tokens: bool,
    pub ignore_eos: bool,
    pub top_k: i64,
    pub has_top_k: bool,
    pub top_p: f32,
    pub has_top_p: bool,
    pub session_id: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub frequency_penalty: f32,
    pub has_frequency_penalty: bool,
    pub presence_penalty: f32,
    pub has_presence_penalty: bool,
    pub stop_sequences: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<&'a str>>>>,
    pub thinking: bool,
    pub has_thinking: bool,
    pub mcp_mode: bool,
    pub has_mcp_mode: bool,
    pub grammar_json: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for SamplingParamsArgs<'a> {
  #[inline]
  fn default() -> Self {
    SamplingParamsArgs {
      temperature: 0.0,
      has_temperature: false,
      max_tokens: 0,
      has_max_tokens: false,
      ignore_eos: false,
      top_k: 0,
      has_top_k: false,
      top_p: 0.0,
      has_top_p: false,
      session_id: None,
      frequency_penalty: 0.0,
      has_frequency_penalty: false,
      presence_penalty: 0.0,
      has_presence_penalty: false,
      stop_sequences: None,
      thinking: false,
      has_thinking: false,
      mcp_mode: false,
      has_mcp_mode: false,
      grammar_json: None,
    }
  }
}

pub struct SamplingParamsBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SamplingParamsBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_temperature(&mut self, temperature: f32) {
    self.fbb_.push_slot::<f32>(SamplingParams::VT_TEMPERATURE, temperature, 0.0);
  }
  #[inline]
  pub fn add_has_temperature(&mut self, has_temperature: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_TEMPERATURE, has_temperature, false);
  }
  #[inline]
  pub fn add_max_tokens(&mut self, max_tokens: u64) {
    self.fbb_.push_slot::<u64>(SamplingParams::VT_MAX_TOKENS, max_tokens, 0);
  }
  #[inline]
  pub fn add_has_max_tokens(&mut self, has_max_tokens: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_MAX_TOKENS, has_max_tokens, false);
  }
  #[inline]
  pub fn add_ignore_eos(&mut self, ignore_eos: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_IGNORE_EOS, ignore_eos, false);
  }
  #[inline]
  pub fn add_top_k(&mut self, top_k: i64) {
    self.fbb_.push_slot::<i64>(SamplingParams::VT_TOP_K, top_k, 0);
  }
  #[inline]
  pub fn add_has_top_k(&mut self, has_top_k: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_TOP_K, has_top_k, false);
  }
  #[inline]
  pub fn add_top_p(&mut self, top_p: f32) {
    self.fbb_.push_slot::<f32>(SamplingParams::VT_TOP_P, top_p, 0.0);
  }
  #[inline]
  pub fn add_has_top_p(&mut self, has_top_p: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_TOP_P, has_top_p, false);
  }
  #[inline]
  pub fn add_session_id(&mut self, session_id: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SamplingParams::VT_SESSION_ID, session_id);
  }
  #[inline]
  pub fn add_frequency_penalty(&mut self, frequency_penalty: f32) {
    self.fbb_.push_slot::<f32>(SamplingParams::VT_FREQUENCY_PENALTY, frequency_penalty, 0.0);
  }
  #[inline]
  pub fn add_has_frequency_penalty(&mut self, has_frequency_penalty: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_FREQUENCY_PENALTY, has_frequency_penalty, false);
  }
  #[inline]
  pub fn add_presence_penalty(&mut self, presence_penalty: f32) {
    self.fbb_.push_slot::<f32>(SamplingParams::VT_PRESENCE_PENALTY, presence_penalty, 0.0);
  }
  #[inline]
  pub fn add_has_presence_penalty(&mut self, has_presence_penalty: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_PRESENCE_PENALTY, has_presence_penalty, false);
  }
  #[inline]
  pub fn add_stop_sequences(&mut self, stop_sequences: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<&'b  str>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SamplingParams::VT_STOP_SEQUENCES, stop_sequences);
  }
  #[inline]
  pub fn add_thinking(&mut self, thinking: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_THINKING, thinking, false);
  }
  #[inline]
  pub fn add_has_thinking(&mut self, has_thinking: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_THINKING, has_thinking, false);
  }
  #[inline]
  pub fn add_mcp_mode(&mut self, mcp_mode: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_MCP_MODE, mcp_mode, false);
  }
  #[inline]
  pub fn add_has_mcp_mode(&mut self, has_mcp_mode: bool) {
    self.fbb_.push_slot::<bool>(SamplingParams::VT_HAS_MCP_MODE, has_mcp_mode, false);
  }
  #[inline]
  pub fn add_grammar_json(&mut self, grammar_json: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(SamplingParams::VT_GRAMMAR_JSON, grammar_json);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SamplingParamsBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SamplingParamsBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SamplingParams<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SamplingParams<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SamplingParams");
      ds.field("temperature", &self.temperature());
      ds.field("has_temperature", &self.has_temperature());
      ds.field("max_tokens", &self.max_tokens());
      ds.field("has_max_tokens", &self.has_max_tokens());
      ds.field("ignore_eos", &self.ignore_eos());
      ds.field("top_k", &self.top_k());
      ds.field("has_top_k", &self.has_top_k());
      ds.field("top_p", &self.top_p());
      ds.field("has_top_p", &self.has_top_p());
      ds.field("session_id", &self.session_id());
      ds.field("frequency_penalty", &self.frequency_penalty());
      ds.field("has_frequency_penalty", &self.has_frequency_penalty());
      ds.field("presence_penalty", &self.presence_penalty());
      ds.field("has_presence_penalty", &self.has_presence_penalty());
      ds.field("stop_sequences", &self.stop_sequences());
      ds.field("thinking", &self.thinking());
      ds.field("has_thinking", &self.has_thinking());
      ds.field("mcp_mode", &self.mcp_mode());
      ds.field("has_mcp_mode", &self.has_mcp_mode());
      ds.field("grammar_json", &self.grammar_json());
      ds.finish()
  }
}
pub enum ImageDataOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ImageData<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ImageData<'a> {
  type Inner = ImageData<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ImageData<'a> {
  pub const VT_RAW: ::flatbuffers::VOffsetT = 4;
  pub const VT_SHAPE: ::flatbuffers::VOffsetT = 6;
  pub const VT_PATCHES_FIRST: ::flatbuffers::VOffsetT = 8;
  pub const VT_PATCHES_SECOND: ::flatbuffers::VOffsetT = 10;
  pub const VT_IMAGE_IDX: ::flatbuffers::VOffsetT = 12;
  pub const VT_IMAGE_TOKEN_OFFSET: ::flatbuffers::VOffsetT = 14;
  pub const VT_TOKENS_PER_IMAGE: ::flatbuffers::VOffsetT = 16;
  pub const VT_IMAGE_TOKEN_ID: ::flatbuffers::VOffsetT = 18;
  pub const VT_HAS_IMAGE_TOKEN_ID: ::flatbuffers::VOffsetT = 20;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ImageData { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ImageDataArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ImageData<'bldr>> {
    let mut builder = ImageDataBuilder::new(_fbb);
    builder.add_image_token_offset(args.image_token_offset);
    builder.add_image_token_id(args.image_token_id);
    if let Some(x) = args.tokens_per_image { builder.add_tokens_per_image(x); }
    builder.add_image_idx(args.image_idx);
    if let Some(x) = args.patches_second { builder.add_patches_second(x); }
    if let Some(x) = args.patches_first { builder.add_patches_first(x); }
    if let Some(x) = args.shape { builder.add_shape(x); }
    if let Some(x) = args.raw { builder.add_raw(x); }
    builder.add_has_image_token_id(args.has_image_token_id);
    builder.finish()
  }


  #[inline]
  pub fn raw(&self) -> Option<::flatbuffers::Vector<'a, u8>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u8>>>(ImageData::VT_RAW, None)}
  }
  #[inline]
  pub fn shape(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(ImageData::VT_SHAPE, None)}
  }
  #[inline]
  pub fn patches_first(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(ImageData::VT_PATCHES_FIRST, None)}
  }
  #[inline]
  pub fn patches_second(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(ImageData::VT_PATCHES_SECOND, None)}
  }
  #[inline]
  pub fn image_idx(&self) -> i32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<i32>(ImageData::VT_IMAGE_IDX, Some(0)).unwrap()}
  }
  #[inline]
  pub fn image_token_offset(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(ImageData::VT_IMAGE_TOKEN_OFFSET, Some(0)).unwrap()}
  }
  #[inline]
  pub fn tokens_per_image(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(ImageData::VT_TOKENS_PER_IMAGE, None)}
  }
  #[inline]
  pub fn image_token_id(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(ImageData::VT_IMAGE_TOKEN_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_image_token_id(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ImageData::VT_HAS_IMAGE_TOKEN_ID, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for ImageData<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u8>>>("raw", Self::VT_RAW, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("shape", Self::VT_SHAPE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("patches_first", Self::VT_PATCHES_FIRST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("patches_second", Self::VT_PATCHES_SECOND, false)?
     .visit_field::<i32>("image_idx", Self::VT_IMAGE_IDX, false)?
     .visit_field::<u64>("image_token_offset", Self::VT_IMAGE_TOKEN_OFFSET, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("tokens_per_image", Self::VT_TOKENS_PER_IMAGE, false)?
     .visit_field::<u32>("image_token_id", Self::VT_IMAGE_TOKEN_ID, false)?
     .visit_field::<bool>("has_image_token_id", Self::VT_HAS_IMAGE_TOKEN_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct ImageDataArgs<'a> {
    pub raw: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u8>>>,
    pub shape: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub patches_first: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub patches_second: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub image_idx: i32,
    pub image_token_offset: u64,
    pub tokens_per_image: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub image_token_id: u32,
    pub has_image_token_id: bool,
}
impl<'a> Default for ImageDataArgs<'a> {
  #[inline]
  fn default() -> Self {
    ImageDataArgs {
      raw: None,
      shape: None,
      patches_first: None,
      patches_second: None,
      image_idx: 0,
      image_token_offset: 0,
      tokens_per_image: None,
      image_token_id: 0,
      has_image_token_id: false,
    }
  }
}

pub struct ImageDataBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ImageDataBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_raw(&mut self, raw: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u8>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageData::VT_RAW, raw);
  }
  #[inline]
  pub fn add_shape(&mut self, shape: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageData::VT_SHAPE, shape);
  }
  #[inline]
  pub fn add_patches_first(&mut self, patches_first: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageData::VT_PATCHES_FIRST, patches_first);
  }
  #[inline]
  pub fn add_patches_second(&mut self, patches_second: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageData::VT_PATCHES_SECOND, patches_second);
  }
  #[inline]
  pub fn add_image_idx(&mut self, image_idx: i32) {
    self.fbb_.push_slot::<i32>(ImageData::VT_IMAGE_IDX, image_idx, 0);
  }
  #[inline]
  pub fn add_image_token_offset(&mut self, image_token_offset: u64) {
    self.fbb_.push_slot::<u64>(ImageData::VT_IMAGE_TOKEN_OFFSET, image_token_offset, 0);
  }
  #[inline]
  pub fn add_tokens_per_image(&mut self, tokens_per_image: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ImageData::VT_TOKENS_PER_IMAGE, tokens_per_image);
  }
  #[inline]
  pub fn add_image_token_id(&mut self, image_token_id: u32) {
    self.fbb_.push_slot::<u32>(ImageData::VT_IMAGE_TOKEN_ID, image_token_id, 0);
  }
  #[inline]
  pub fn add_has_image_token_id(&mut self, has_image_token_id: bool) {
    self.fbb_.push_slot::<bool>(ImageData::VT_HAS_IMAGE_TOKEN_ID, has_image_token_id, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ImageDataBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ImageDataBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ImageData<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ImageData<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ImageData");
      ds.field("raw", &self.raw());
      ds.field("shape", &self.shape());
      ds.field("patches_first", &self.patches_first());
      ds.field("patches_second", &self.patches_second());
      ds.field("image_idx", &self.image_idx());
      ds.field("image_token_offset", &self.image_token_offset());
      ds.field("tokens_per_image", &self.tokens_per_image());
      ds.field("image_token_id", &self.image_token_id());
      ds.field("has_image_token_id", &self.has_image_token_id());
      ds.finish()
  }
}
pub enum SequenceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Sequence<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Sequence<'a> {
  type Inner = Sequence<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Sequence<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_CREATED_TIME: ::flatbuffers::VOffsetT = 6;
  pub const VT_SWAPPED_TIME: ::flatbuffers::VOffsetT = 8;
  pub const VT_HAS_SWAPPED_TIME: ::flatbuffers::VOffsetT = 10;
  pub const VT_STATUS: ::flatbuffers::VOffsetT = 12;
  pub const VT_TOKEN_IDS: ::flatbuffers::VOffsetT = 14;
  pub const VT_OUTPUT_IDS: ::flatbuffers::VOffsetT = 16;
  pub const VT_BLOCK_TABLE: ::flatbuffers::VOffsetT = 18;
  pub const VT_NUM_CACHED_TOKENS: ::flatbuffers::VOffsetT = 20;
  pub const VT_MAMBA_PREFIX_HASH: ::flatbuffers::VOffsetT = 22;
  pub const VT_HAS_MAMBA_PREFIX_HASH: ::flatbuffers::VOffsetT = 24;
  pub const VT_LAST_TOKEN: ::flatbuffers::VOffsetT = 26;
  pub const VT_BLOCK_SIZE: ::flatbuffers::VOffsetT = 28;
  pub const VT_SAMPLING_PARAMS: ::flatbuffers::VOffsetT = 30;
  pub const VT_PD_FIRST_TOKEN: ::flatbuffers::VOffsetT = 32;
  pub const VT_HAS_PD_FIRST_TOKEN: ::flatbuffers::VOffsetT = 34;
  pub const VT_IMAGES: ::flatbuffers::VOffsetT = 36;
  pub const VT_IS_TOOL_CALL_END: ::flatbuffers::VOffsetT = 38;
  pub const VT_HIT_STOP_SEQUENCE: ::flatbuffers::VOffsetT = 40;
  pub const VT_STOP_SEQUENCE: ::flatbuffers::VOffsetT = 42;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Sequence { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SequenceArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Sequence<'bldr>> {
    let mut builder = SequenceBuilder::new(_fbb);
    builder.add_block_size(args.block_size);
    builder.add_mamba_prefix_hash(args.mamba_prefix_hash);
    builder.add_num_cached_tokens(args.num_cached_tokens);
    builder.add_swapped_time(args.swapped_time);
    builder.add_created_time(args.created_time);
    builder.add_id(args.id);
    if let Some(x) = args.stop_sequence { builder.add_stop_sequence(x); }
    if let Some(x) = args.images { builder.add_images(x); }
    builder.add_pd_first_token(args.pd_first_token);
    if let Some(x) = args.sampling_params { builder.add_sampling_params(x); }
    builder.add_last_token(args.last_token);
    if let Some(x) = args.block_table { builder.add_block_table(x); }
    if let Some(x) = args.output_ids { builder.add_output_ids(x); }
    if let Some(x) = args.token_ids { builder.add_token_ids(x); }
    builder.add_hit_stop_sequence(args.hit_stop_sequence);
    builder.add_is_tool_call_end(args.is_tool_call_end);
    builder.add_has_pd_first_token(args.has_pd_first_token);
    builder.add_has_mamba_prefix_hash(args.has_mamba_prefix_hash);
    builder.add_status(args.status);
    builder.add_has_swapped_time(args.has_swapped_time);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn created_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_CREATED_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn swapped_time(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_SWAPPED_TIME, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_swapped_time(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Sequence::VT_HAS_SWAPPED_TIME, Some(false)).unwrap()}
  }
  #[inline]
  pub fn status(&self) -> SequenceStatus {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<SequenceStatus>(Sequence::VT_STATUS, Some(SequenceStatus::Waiting)).unwrap()}
  }
  #[inline]
  pub fn token_ids(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(Sequence::VT_TOKEN_IDS, None)}
  }
  #[inline]
  pub fn output_ids(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(Sequence::VT_OUTPUT_IDS, None)}
  }
  #[inline]
  pub fn block_table(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(Sequence::VT_BLOCK_TABLE, None)}
  }
  #[inline]
  pub fn num_cached_tokens(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_NUM_CACHED_TOKENS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn mamba_prefix_hash(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_MAMBA_PREFIX_HASH, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_mamba_prefix_hash(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Sequence::VT_HAS_MAMBA_PREFIX_HASH, Some(false)).unwrap()}
  }
  #[inline]
  pub fn last_token(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Sequence::VT_LAST_TOKEN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn block_size(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Sequence::VT_BLOCK_SIZE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn sampling_params(&self) -> Option<SamplingParams<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SamplingParams>>(Sequence::VT_SAMPLING_PARAMS, None)}
  }
  #[inline]
  pub fn pd_first_token(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(Sequence::VT_PD_FIRST_TOKEN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_pd_first_token(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Sequence::VT_HAS_PD_FIRST_TOKEN, Some(false)).unwrap()}
  }
  #[inline]
  pub fn images(&self) -> Option<ImageData<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<ImageData>>(Sequence::VT_IMAGES, None)}
  }
  #[inline]
  pub fn is_tool_call_end(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Sequence::VT_IS_TOOL_CALL_END, Some(false)).unwrap()}
  }
  #[inline]
  pub fn hit_stop_sequence(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(Sequence::VT_HIT_STOP_SEQUENCE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn stop_sequence(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Sequence::VT_STOP_SEQUENCE, None)}
  }
}

impl ::flatbuffers::Verifiable for Sequence<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<u64>("created_time", Self::VT_CREATED_TIME, false)?
     .visit_field::<u64>("swapped_time", Self::VT_SWAPPED_TIME, false)?
     .visit_field::<bool>("has_swapped_time", Self::VT_HAS_SWAPPED_TIME, false)?
     .visit_field::<SequenceStatus>("status", Self::VT_STATUS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("token_ids", Self::VT_TOKEN_IDS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("output_ids", Self::VT_OUTPUT_IDS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("block_table", Self::VT_BLOCK_TABLE, false)?
     .visit_field::<u64>("num_cached_tokens", Self::VT_NUM_CACHED_TOKENS, false)?
     .visit_field::<u64>("mamba_prefix_hash", Self::VT_MAMBA_PREFIX_HASH, false)?
     .visit_field::<bool>("has_mamba_prefix_hash", Self::VT_HAS_MAMBA_PREFIX_HASH, false)?
     .visit_field::<u32>("last_token", Self::VT_LAST_TOKEN, false)?
     .visit_field::<u64>("block_size", Self::VT_BLOCK_SIZE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<SamplingParams>>("sampling_params", Self::VT_SAMPLING_PARAMS, false)?
     .visit_field::<u32>("pd_first_token", Self::VT_PD_FIRST_TOKEN, false)?
     .visit_field::<bool>("has_pd_first_token", Self::VT_HAS_PD_FIRST_TOKEN, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<ImageData>>("images", Self::VT_IMAGES, false)?
     .visit_field::<bool>("is_tool_call_end", Self::VT_IS_TOOL_CALL_END, false)?
     .visit_field::<bool>("hit_stop_sequence", Self::VT_HIT_STOP_SEQUENCE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("stop_sequence", Self::VT_STOP_SEQUENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct SequenceArgs<'a> {
    pub id: u64,
    pub created_time: u64,
    pub swapped_time: u64,
    pub has_swapped_time: bool,
    pub status: SequenceStatus,
    pub token_ids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
    pub output_ids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
    pub block_table: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
    pub num_cached_tokens: u64,
    pub mamba_prefix_hash: u64,
    pub has_mamba_prefix_hash: bool,
    pub last_token: u32,
    pub block_size: u64,
    pub sampling_params: Option<::flatbuffers::WIPOffset<SamplingParams<'a>>>,
    pub pd_first_token: u32,
    pub has_pd_first_token: bool,
    pub images: Option<::flatbuffers::WIPOffset<ImageData<'a>>>,
    pub is_tool_call_end: bool,
    pub hit_stop_sequence: bool,
    pub stop_sequence: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for SequenceArgs<'a> {
  #[inline]
  fn default() -> Self {
    SequenceArgs {
      id: 0,
      created_time: 0,
      swapped_time: 0,
      has_swapped_time: false,
      status: SequenceStatus::Waiting,
      token_ids: None,
      output_ids: None,
      block_table: None,
      num_cached_tokens: 0,
      mamba_prefix_hash: 0,
      has_mamba_prefix_hash: false,
      last_token: 0,
      block_size: 0,
      sampling_params: None,
      pd_first_token: 0,
      has_pd_first_token: false,
      images: None,
      is_tool_call_end: false,
      hit_stop_sequence: false,
      stop_sequence: None,
    }
  }
}

pub struct SequenceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SequenceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_created_time(&mut self, created_time: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_CREATED_TIME, created_time, 0);
  }
  #[inline]
  pub fn add_swapped_time(&mut self, swapped_time: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_SWAPPED_TIME, swapped_time, 0);
  }
  #[inline]
  pub fn add_has_swapped_time(&mut self, has_swapped_time: bool) {
    self.fbb_.push_slot::<bool>(Sequence::VT_HAS_SWAPPED_TIME, has_swapped_time, false);
  }
  #[inline]
  pub fn add_status(&mut self, status: SequenceStatus) {
    self.fbb_.push_slot::<SequenceStatus>(Sequence::VT_STATUS, status, SequenceStatus::Waiting);
  }
  #[inline]
  pub fn add_token_ids(&mut self, token_ids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Sequence::VT_TOKEN_IDS, token_ids);
  }
  #[inline]
  pub fn add_output_ids(&mut self, output_ids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Sequence::VT_OUTPUT_IDS, output_ids);
  }
  #[inline]
  pub fn add_block_table(&mut self, block_table: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Sequence::VT_BLOCK_TABLE, block_table);
  }
  #[inline]
  pub fn add_num_cached_tokens(&mut self, num_cached_tokens: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_NUM_CACHED_TOKENS, num_cached_tokens, 0);
  }
  #[inline]
  pub fn add_mamba_prefix_hash(&mut self, mamba_prefix_hash: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_MAMBA_PREFIX_HASH, mamba_prefix_hash, 0);
  }
  #[inline]
  pub fn add_has_mamba_prefix_hash(&mut self, has_mamba_prefix_hash: bool) {
    self.fbb_.push_slot::<bool>(Sequence::VT_HAS_MAMBA_PREFIX_HASH, has_mamba_prefix_hash, false);
  }
  #[inline]
  pub fn add_last_token(&mut self, last_token: u32) {
    self.fbb_.push_slot::<u32>(Sequence::VT_LAST_TOKEN, last_token, 0);
  }
  #[inline]
  pub fn add_block_size(&mut self, block_size: u64) {
    self.fbb_.push_slot::<u64>(Sequence::VT_BLOCK_SIZE, block_size, 0);
  }
  #[inline]
  pub fn add_sampling_params(&mut self, sampling_params: ::flatbuffers::WIPOffset<SamplingParams<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<SamplingParams>>(Sequence::VT_SAMPLING_PARAMS, sampling_params);
  }
  #[inline]
  pub fn add_pd_first_token(&mut self, pd_first_token: u32) {
    self.fbb_.push_slot::<u32>(Sequence::VT_PD_FIRST_TOKEN, pd_first_token, 0);
  }
  #[inline]
  pub fn add_has_pd_first_token(&mut self, has_pd_first_token: bool) {
    self.fbb_.push_slot::<bool>(Sequence::VT_HAS_PD_FIRST_TOKEN, has_pd_first_token, false);
  }
  #[inline]
  pub fn add_images(&mut self, images: ::flatbuffers::WIPOffset<ImageData<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<ImageData>>(Sequence::VT_IMAGES, images);
  }
  #[inline]
  pub fn add_is_tool_call_end(&mut self, is_tool_call_end: bool) {
    self.fbb_.push_slot::<bool>(Sequence::VT_IS_TOOL_CALL_END, is_tool_call_end, false);
  }
  #[inline]
  pub fn add_hit_stop_sequence(&mut self, hit_stop_sequence: bool) {
    self.fbb_.push_slot::<bool>(Sequence::VT_HIT_STOP_SEQUENCE, hit_stop_sequence, false);
  }
  #[inline]
  pub fn add_stop_sequence(&mut self, stop_sequence: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Sequence::VT_STOP_SEQUENCE, stop_sequence);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SequenceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SequenceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Sequence<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Sequence<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Sequence");
      ds.field("id", &self.id());
      ds.field("created_time", &self.created_time());
      ds.field("swapped_time", &self.swapped_time());
      ds.field("has_swapped_time", &self.has_swapped_time());
      ds.field("status", &self.status());
      ds.field("token_ids", &self.token_ids());
      ds.field("output_ids", &self.output_ids());
      ds.field("block_table", &self.block_table());
      ds.field("num_cached_tokens", &self.num_cached_tokens());
      ds.field("mamba_prefix_hash", &self.mamba_prefix_hash());
      ds.field("has_mamba_prefix_hash", &self.has_mamba_prefix_hash());
      ds.field("last_token", &self.last_token());
      ds.field("block_size", &self.block_size());
      ds.field("sampling_params", &self.sampling_params());
      ds.field("pd_first_token", &self.pd_first_token());
      ds.field("has_pd_first_token", &self.has_pd_first_token());
      ds.field("images", &self.images());
      ds.field("is_tool_call_end", &self.is_tool_call_end());
      ds.field("hit_stop_sequence", &self.hit_stop_sequence());
      ds.field("stop_sequence", &self.stop_sequence());
      ds.finish()
  }
}
pub enum DecodeSequenceOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct DecodeSequence<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for DecodeSequence<'a> {
  type Inner = DecodeSequence<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> DecodeSequence<'a> {
  pub const VT_ID: ::flatbuffers::VOffsetT = 4;
  pub const VT_LAST_TOKEN: ::flatbuffers::VOffsetT = 6;
  pub const VT_LEN: ::flatbuffers::VOffsetT = 8;
  pub const VT_LAST_BLOCK_TOKENS: ::flatbuffers::VOffsetT = 10;
  pub const VT_BLOCK_TABLE_LAST: ::flatbuffers::VOffsetT = 12;
  pub const VT_BLOCK_TABLES: ::flatbuffers::VOffsetT = 14;
  pub const VT_SAMPLING_PARAMS: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    DecodeSequence { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args DecodeSequenceArgs<'args>
  ) -> ::flatbuffers::WIPOffset<DecodeSequence<'bldr>> {
    let mut builder = DecodeSequenceBuilder::new(_fbb);
    builder.add_last_block_tokens(args.last_block_tokens);
    builder.add_len(args.len);
    builder.add_id(args.id);
    if let Some(x) = args.sampling_params { builder.add_sampling_params(x); }
    if let Some(x) = args.block_tables { builder.add_block_tables(x); }
    builder.add_block_table_last(args.block_table_last);
    builder.add_last_token(args.last_token);
    builder.finish()
  }


  #[inline]
  pub fn id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DecodeSequence::VT_ID, Some(0)).unwrap()}
  }
  #[inline]
  pub fn last_token(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(DecodeSequence::VT_LAST_TOKEN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn len(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DecodeSequence::VT_LEN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn last_block_tokens(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(DecodeSequence::VT_LAST_BLOCK_TOKENS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn block_table_last(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(DecodeSequence::VT_BLOCK_TABLE_LAST, Some(0)).unwrap()}
  }
  #[inline]
  pub fn block_tables(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(DecodeSequence::VT_BLOCK_TABLES, None)}
  }
  #[inline]
  pub fn sampling_params(&self) -> Option<SamplingParams<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<SamplingParams>>(DecodeSequence::VT_SAMPLING_PARAMS, None)}
  }
}

impl ::flatbuffers::Verifiable for DecodeSequence<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("id", Self::VT_ID, false)?
     .visit_field::<u32>("last_token", Self::VT_LAST_TOKEN, false)?
     .visit_field::<u64>("len", Self::VT_LEN, false)?
     .visit_field::<u64>("last_block_tokens", Self::VT_LAST_BLOCK_TOKENS, false)?
     .visit_field::<u32>("block_table_last", Self::VT_BLOCK_TABLE_LAST, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("block_tables", Self::VT_BLOCK_TABLES, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<SamplingParams>>("sampling_params", Self::VT_SAMPLING_PARAMS, false)?
     .finish();
    Ok(())
  }
}
pub struct DecodeSequenceArgs<'a> {
    pub id: u64,
    pub last_token: u32,
    pub len: u64,
    pub last_block_tokens: u64,
    pub block_table_last: u32,
    pub block_tables: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
    pub sampling_params: Option<::flatbuffers::WIPOffset<SamplingParams<'a>>>,
}
impl<'a> Default for DecodeSequenceArgs<'a> {
  #[inline]
  fn default() -> Self {
    DecodeSequenceArgs {
      id: 0,
      last_token: 0,
      len: 0,
      last_block_tokens: 0,
      block_table_last: 0,
      block_tables: None,
      sampling_params: None,
    }
  }
}

pub struct DecodeSequenceBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> DecodeSequenceBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_id(&mut self, id: u64) {
    self.fbb_.push_slot::<u64>(DecodeSequence::VT_ID, id, 0);
  }
  #[inline]
  pub fn add_last_token(&mut self, last_token: u32) {
    self.fbb_.push_slot::<u32>(DecodeSequence::VT_LAST_TOKEN, last_token, 0);
  }
  #[inline]
  pub fn add_len(&mut self, len: u64) {
    self.fbb_.push_slot::<u64>(DecodeSequence::VT_LEN, len, 0);
  }
  #[inline]
  pub fn add_last_block_tokens(&mut self, last_block_tokens: u64) {
    self.fbb_.push_slot::<u64>(DecodeSequence::VT_LAST_BLOCK_TOKENS, last_block_tokens, 0);
  }
  #[inline]
  pub fn add_block_table_last(&mut self, block_table_last: u32) {
    self.fbb_.push_slot::<u32>(DecodeSequence::VT_BLOCK_TABLE_LAST, block_table_last, 0);
  }
  #[inline]
  pub fn add_block_tables(&mut self, block_tables: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(DecodeSequence::VT_BLOCK_TABLES, block_tables);
  }
  #[inline]
  pub fn add_sampling_params(&mut self, sampling_params: ::flatbuffers::WIPOffset<SamplingParams<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<SamplingParams>>(DecodeSequence::VT_SAMPLING_PARAMS, sampling_params);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> DecodeSequenceBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    DecodeSequenceBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<DecodeSequence<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for DecodeSequence<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("DecodeSequence");
      ds.field("id", &self.id());
      ds.field("last_token", &self.last_token());
      ds.field("len", &self.len());
      ds.field("last_block_tokens", &self.last_block_tokens());
      ds.field("block_table_last", &self.block_table_last());
      ds.field("block_tables", &self.block_tables());
      ds.field("sampling_params", &self.sampling_params());
      ds.finish()
  }
}
pub enum RunPrefillPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RunPrefillPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RunPrefillPayload<'a> {
  type Inner = RunPrefillPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RunPrefillPayload<'a> {
  pub const VT_SEQUENCES: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RunPrefillPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RunPrefillPayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RunPrefillPayload<'bldr>> {
    let mut builder = RunPrefillPayloadBuilder::new(_fbb);
    if let Some(x) = args.sequences { builder.add_sequences(x); }
    builder.finish()
  }


  #[inline]
  pub fn sequences(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Sequence<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Sequence>>>>(RunPrefillPayload::VT_SEQUENCES, None)}
  }
}

impl ::flatbuffers::Verifiable for RunPrefillPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<Sequence>>>>("sequences", Self::VT_SEQUENCES, false)?
     .finish();
    Ok(())
  }
}
pub struct RunPrefillPayloadArgs<'a> {
    pub sequences: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<Sequence<'a>>>>>,
}
impl<'a> Default for RunPrefillPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    RunPrefillPayloadArgs {
      sequences: None,
    }
  }
}

pub struct RunPrefillPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RunPrefillPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequences(&mut self, sequences: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<Sequence<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RunPrefillPayload::VT_SEQUENCES, sequences);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RunPrefillPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RunPrefillPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RunPrefillPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RunPrefillPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RunPrefillPayload");
      ds.field("sequences", &self.sequences());
      ds.finish()
  }
}
pub enum RunDecodePayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RunDecodePayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RunDecodePayload<'a> {
  type Inner = RunDecodePayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RunDecodePayload<'a> {
  pub const VT_SEQUENCES: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RunDecodePayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RunDecodePayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RunDecodePayload<'bldr>> {
    let mut builder = RunDecodePayloadBuilder::new(_fbb);
    if let Some(x) = args.sequences { builder.add_sequences(x); }
    builder.finish()
  }


  #[inline]
  pub fn sequences(&self) -> Option<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DecodeSequence<'a>>>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DecodeSequence>>>>(RunDecodePayload::VT_SEQUENCES, None)}
  }
}

impl ::flatbuffers::Verifiable for RunDecodePayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, ::flatbuffers::ForwardsUOffset<DecodeSequence>>>>("sequences", Self::VT_SEQUENCES, false)?
     .finish();
    Ok(())
  }
}
pub struct RunDecodePayloadArgs<'a> {
    pub sequences: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, ::flatbuffers::ForwardsUOffset<DecodeSequence<'a>>>>>,
}
impl<'a> Default for RunDecodePayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    RunDecodePayloadArgs {
      sequences: None,
    }
  }
}

pub struct RunDecodePayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RunDecodePayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequences(&mut self, sequences: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , ::flatbuffers::ForwardsUOffset<DecodeSequence<'b >>>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RunDecodePayload::VT_SEQUENCES, sequences);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RunDecodePayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RunDecodePayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RunDecodePayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RunDecodePayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RunDecodePayload");
      ds.field("sequences", &self.sequences());
      ds.finish()
  }
}
pub enum SingleIdPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SingleIdPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SingleIdPayload<'a> {
  type Inner = SingleIdPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SingleIdPayload<'a> {
  pub const VT_SEQUENCE_ID: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SingleIdPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SingleIdPayloadArgs
  ) -> ::flatbuffers::WIPOffset<SingleIdPayload<'bldr>> {
    let mut builder = SingleIdPayloadBuilder::new(_fbb);
    builder.add_sequence_id(args.sequence_id);
    builder.finish()
  }


  #[inline]
  pub fn sequence_id(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(SingleIdPayload::VT_SEQUENCE_ID, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SingleIdPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("sequence_id", Self::VT_SEQUENCE_ID, false)?
     .finish();
    Ok(())
  }
}
pub struct SingleIdPayloadArgs {
    pub sequence_id: u64,
}
impl<'a> Default for SingleIdPayloadArgs {
  #[inline]
  fn default() -> Self {
    SingleIdPayloadArgs {
      sequence_id: 0,
    }
  }
}

pub struct SingleIdPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SingleIdPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequence_id(&mut self, sequence_id: u64) {
    self.fbb_.push_slot::<u64>(SingleIdPayload::VT_SEQUENCE_ID, sequence_id, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SingleIdPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SingleIdPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SingleIdPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SingleIdPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SingleIdPayload");
      ds.field("sequence_id", &self.sequence_id());
      ds.finish()
  }
}
pub enum SingleSequencePayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SingleSequencePayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SingleSequencePayload<'a> {
  type Inner = SingleSequencePayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SingleSequencePayload<'a> {
  pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SingleSequencePayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SingleSequencePayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SingleSequencePayload<'bldr>> {
    let mut builder = SingleSequencePayloadBuilder::new(_fbb);
    if let Some(x) = args.sequence { builder.add_sequence(x); }
    builder.finish()
  }


  #[inline]
  pub fn sequence(&self) -> Option<Sequence<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Sequence>>(SingleSequencePayload::VT_SEQUENCE, None)}
  }
}

impl ::flatbuffers::Verifiable for SingleSequencePayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Sequence>>("sequence", Self::VT_SEQUENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct SingleSequencePayloadArgs<'a> {
    pub sequence: Option<::flatbuffers::WIPOffset<Sequence<'a>>>,
}
impl<'a> Default for SingleSequencePayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    SingleSequencePayloadArgs {
      sequence: None,
    }
  }
}

pub struct SingleSequencePayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SingleSequencePayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequence(&mut self, sequence: ::flatbuffers::WIPOffset<Sequence<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Sequence>>(SingleSequencePayload::VT_SEQUENCE, sequence);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SingleSequencePayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SingleSequencePayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SingleSequencePayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SingleSequencePayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SingleSequencePayload");
      ds.field("sequence", &self.sequence());
      ds.finish()
  }
}
pub enum AvailableTokensPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct AvailableTokensPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for AvailableTokensPayload<'a> {
  type Inner = AvailableTokensPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> AvailableTokensPayload<'a> {
  pub const VT_AVAILABLE_TOKENS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    AvailableTokensPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args AvailableTokensPayloadArgs
  ) -> ::flatbuffers::WIPOffset<AvailableTokensPayload<'bldr>> {
    let mut builder = AvailableTokensPayloadBuilder::new(_fbb);
    builder.add_available_tokens(args.available_tokens);
    builder.finish()
  }


  #[inline]
  pub fn available_tokens(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(AvailableTokensPayload::VT_AVAILABLE_TOKENS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for AvailableTokensPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("available_tokens", Self::VT_AVAILABLE_TOKENS, false)?
     .finish();
    Ok(())
  }
}
pub struct AvailableTokensPayloadArgs {
    pub available_tokens: u64,
}
impl<'a> Default for AvailableTokensPayloadArgs {
  #[inline]
  fn default() -> Self {
    AvailableTokensPayloadArgs {
      available_tokens: 0,
    }
  }
}

pub struct AvailableTokensPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> AvailableTokensPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_available_tokens(&mut self, available_tokens: u64) {
    self.fbb_.push_slot::<u64>(AvailableTokensPayload::VT_AVAILABLE_TOKENS, available_tokens, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> AvailableTokensPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    AvailableTokensPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<AvailableTokensPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for AvailableTokensPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("AvailableTokensPayload");
      ds.field("available_tokens", &self.available_tokens());
      ds.finish()
  }
}
pub enum KvCacheSendPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KvCacheSendPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for KvCacheSendPayload<'a> {
  type Inner = KvCacheSendPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KvCacheSendPayload<'a> {
  pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 4;
  pub const VT_FIRST_TOKEN: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    KvCacheSendPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KvCacheSendPayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<KvCacheSendPayload<'bldr>> {
    let mut builder = KvCacheSendPayloadBuilder::new(_fbb);
    builder.add_first_token(args.first_token);
    if let Some(x) = args.sequence { builder.add_sequence(x); }
    builder.finish()
  }


  #[inline]
  pub fn sequence(&self) -> Option<Sequence<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Sequence>>(KvCacheSendPayload::VT_SEQUENCE, None)}
  }
  #[inline]
  pub fn first_token(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(KvCacheSendPayload::VT_FIRST_TOKEN, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for KvCacheSendPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Sequence>>("sequence", Self::VT_SEQUENCE, false)?
     .visit_field::<u32>("first_token", Self::VT_FIRST_TOKEN, false)?
     .finish();
    Ok(())
  }
}
pub struct KvCacheSendPayloadArgs<'a> {
    pub sequence: Option<::flatbuffers::WIPOffset<Sequence<'a>>>,
    pub first_token: u32,
}
impl<'a> Default for KvCacheSendPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    KvCacheSendPayloadArgs {
      sequence: None,
      first_token: 0,
    }
  }
}

pub struct KvCacheSendPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KvCacheSendPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_sequence(&mut self, sequence: ::flatbuffers::WIPOffset<Sequence<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Sequence>>(KvCacheSendPayload::VT_SEQUENCE, sequence);
  }
  #[inline]
  pub fn add_first_token(&mut self, first_token: u32) {
    self.fbb_.push_slot::<u32>(KvCacheSendPayload::VT_FIRST_TOKEN, first_token, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KvCacheSendPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KvCacheSendPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<KvCacheSendPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for KvCacheSendPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("KvCacheSendPayload");
      ds.field("sequence", &self.sequence());
      ds.field("first_token", &self.first_token());
      ds.finish()
  }
}
pub enum KvCacheSwapPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KvCacheSwapPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for KvCacheSwapPayload<'a> {
  type Inner = KvCacheSwapPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KvCacheSwapPayload<'a> {
  pub const VT_MAPPING_KEYS: ::flatbuffers::VOffsetT = 4;
  pub const VT_MAPPING_VALUES: ::flatbuffers::VOffsetT = 6;
  pub const VT_SWAP_IN: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    KvCacheSwapPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KvCacheSwapPayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<KvCacheSwapPayload<'bldr>> {
    let mut builder = KvCacheSwapPayloadBuilder::new(_fbb);
    if let Some(x) = args.mapping_values { builder.add_mapping_values(x); }
    if let Some(x) = args.mapping_keys { builder.add_mapping_keys(x); }
    builder.add_swap_in(args.swap_in);
    builder.finish()
  }


  #[inline]
  pub fn mapping_keys(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(KvCacheSwapPayload::VT_MAPPING_KEYS, None)}
  }
  #[inline]
  pub fn mapping_values(&self) -> Option<::flatbuffers::Vector<'a, u64>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u64>>>(KvCacheSwapPayload::VT_MAPPING_VALUES, None)}
  }
  #[inline]
  pub fn swap_in(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(KvCacheSwapPayload::VT_SWAP_IN, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for KvCacheSwapPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("mapping_keys", Self::VT_MAPPING_KEYS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u64>>>("mapping_values", Self::VT_MAPPING_VALUES, false)?
     .visit_field::<bool>("swap_in", Self::VT_SWAP_IN, false)?
     .finish();
    Ok(())
  }
}
pub struct KvCacheSwapPayloadArgs<'a> {
    pub mapping_keys: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub mapping_values: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u64>>>,
    pub swap_in: bool,
}
impl<'a> Default for KvCacheSwapPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    KvCacheSwapPayloadArgs {
      mapping_keys: None,
      mapping_values: None,
      swap_in: false,
    }
  }
}

pub struct KvCacheSwapPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KvCacheSwapPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_mapping_keys(&mut self, mapping_keys: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KvCacheSwapPayload::VT_MAPPING_KEYS, mapping_keys);
  }
  #[inline]
  pub fn add_mapping_values(&mut self, mapping_values: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u64>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KvCacheSwapPayload::VT_MAPPING_VALUES, mapping_values);
  }
  #[inline]
  pub fn add_swap_in(&mut self, swap_in: bool) {
    self.fbb_.push_slot::<bool>(KvCacheSwapPayload::VT_SWAP_IN, swap_in, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KvCacheSwapPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KvCacheSwapPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<KvCacheSwapPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for KvCacheSwapPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("KvCacheSwapPayload");
      ds.field("mapping_keys", &self.mapping_keys());
      ds.field("mapping_values", &self.mapping_values());
      ds.field("swap_in", &self.swap_in());
      ds.finish()
  }
}
pub enum RunResponsePayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct RunResponsePayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for RunResponsePayload<'a> {
  type Inner = RunResponsePayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> RunResponsePayload<'a> {
  pub const VT_OUTPUT_IDS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    RunResponsePayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args RunResponsePayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<RunResponsePayload<'bldr>> {
    let mut builder = RunResponsePayloadBuilder::new(_fbb);
    if let Some(x) = args.output_ids { builder.add_output_ids(x); }
    builder.finish()
  }


  #[inline]
  pub fn output_ids(&self) -> Option<::flatbuffers::Vector<'a, u32>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, u32>>>(RunResponsePayload::VT_OUTPUT_IDS, None)}
  }
}

impl ::flatbuffers::Verifiable for RunResponsePayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, u32>>>("output_ids", Self::VT_OUTPUT_IDS, false)?
     .finish();
    Ok(())
  }
}
pub struct RunResponsePayloadArgs<'a> {
    pub output_ids: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, u32>>>,
}
impl<'a> Default for RunResponsePayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    RunResponsePayloadArgs {
      output_ids: None,
    }
  }
}

pub struct RunResponsePayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> RunResponsePayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_output_ids(&mut self, output_ids: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , u32>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(RunResponsePayload::VT_OUTPUT_IDS, output_ids);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> RunResponsePayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    RunResponsePayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<RunResponsePayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for RunResponsePayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("RunResponsePayload");
      ds.field("output_ids", &self.output_ids());
      ds.finish()
  }
}
pub enum BoolPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BoolPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BoolPayload<'a> {
  type Inner = BoolPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BoolPayload<'a> {
  pub const VT_VALUE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BoolPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BoolPayloadArgs
  ) -> ::flatbuffers::WIPOffset<BoolPayload<'bldr>> {
    let mut builder = BoolPayloadBuilder::new(_fbb);
    builder.add_value(args.value);
    builder.finish()
  }


  #[inline]
  pub fn value(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(BoolPayload::VT_VALUE, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for BoolPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("value", Self::VT_VALUE, false)?
     .finish();
    Ok(())
  }
}
pub struct BoolPayloadArgs {
    pub value: bool,
}
impl<'a> Default for BoolPayloadArgs {
  #[inline]
  fn default() -> Self {
    BoolPayloadArgs {
      value: false,
    }
  }
}

pub struct BoolPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BoolPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_value(&mut self, value: bool) {
    self.fbb_.push_slot::<bool>(BoolPayload::VT_VALUE, value, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BoolPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BoolPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BoolPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BoolPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BoolPayload");
      ds.field("value", &self.value());
      ds.finish()
  }
}
pub enum ReceivePrefillResponsePayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ReceivePrefillResponsePayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ReceivePrefillResponsePayload<'a> {
  type Inner = ReceivePrefillResponsePayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ReceivePrefillResponsePayload<'a> {
  pub const VT_SUCCESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_SEQUENCE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ReceivePrefillResponsePayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ReceivePrefillResponsePayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ReceivePrefillResponsePayload<'bldr>> {
    let mut builder = ReceivePrefillResponsePayloadBuilder::new(_fbb);
    if let Some(x) = args.sequence { builder.add_sequence(x); }
    builder.add_success(args.success);
    builder.finish()
  }


  #[inline]
  pub fn success(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(ReceivePrefillResponsePayload::VT_SUCCESS, Some(false)).unwrap()}
  }
  #[inline]
  pub fn sequence(&self) -> Option<Sequence<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<Sequence>>(ReceivePrefillResponsePayload::VT_SEQUENCE, None)}
  }
}

impl ::flatbuffers::Verifiable for ReceivePrefillResponsePayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("success", Self::VT_SUCCESS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<Sequence>>("sequence", Self::VT_SEQUENCE, false)?
     .finish();
    Ok(())
  }
}
pub struct ReceivePrefillResponsePayloadArgs<'a> {
    pub success: bool,
    pub sequence: Option<::flatbuffers::WIPOffset<Sequence<'a>>>,
}
impl<'a> Default for ReceivePrefillResponsePayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    ReceivePrefillResponsePayloadArgs {
      success: false,
      sequence: None,
    }
  }
}

pub struct ReceivePrefillResponsePayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ReceivePrefillResponsePayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_success(&mut self, success: bool) {
    self.fbb_.push_slot::<bool>(ReceivePrefillResponsePayload::VT_SUCCESS, success, false);
  }
  #[inline]
  pub fn add_sequence(&mut self, sequence: ::flatbuffers::WIPOffset<Sequence<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<Sequence>>(ReceivePrefillResponsePayload::VT_SEQUENCE, sequence);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ReceivePrefillResponsePayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ReceivePrefillResponsePayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ReceivePrefillResponsePayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ReceivePrefillResponsePayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ReceivePrefillResponsePayload");
      ds.field("success", &self.success());
      ds.field("sequence", &self.sequence());
      ds.finish()
  }
}
pub enum KvCacheReceiveResponsePayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KvCacheReceiveResponsePayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for KvCacheReceiveResponsePayload<'a> {
  type Inner = KvCacheReceiveResponsePayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KvCacheReceiveResponsePayload<'a> {
  pub const VT_SUCCESS: ::flatbuffers::VOffsetT = 4;
  pub const VT_FIRST_TOKEN: ::flatbuffers::VOffsetT = 6;
  pub const VT_NUM_TOKENS: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    KvCacheReceiveResponsePayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KvCacheReceiveResponsePayloadArgs
  ) -> ::flatbuffers::WIPOffset<KvCacheReceiveResponsePayload<'bldr>> {
    let mut builder = KvCacheReceiveResponsePayloadBuilder::new(_fbb);
    builder.add_num_tokens(args.num_tokens);
    builder.add_first_token(args.first_token);
    builder.add_success(args.success);
    builder.finish()
  }


  #[inline]
  pub fn success(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(KvCacheReceiveResponsePayload::VT_SUCCESS, Some(false)).unwrap()}
  }
  #[inline]
  pub fn first_token(&self) -> u32 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u32>(KvCacheReceiveResponsePayload::VT_FIRST_TOKEN, Some(0)).unwrap()}
  }
  #[inline]
  pub fn num_tokens(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(KvCacheReceiveResponsePayload::VT_NUM_TOKENS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for KvCacheReceiveResponsePayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("success", Self::VT_SUCCESS, false)?
     .visit_field::<u32>("first_token", Self::VT_FIRST_TOKEN, false)?
     .visit_field::<u64>("num_tokens", Self::VT_NUM_TOKENS, false)?
     .finish();
    Ok(())
  }
}
pub struct KvCacheReceiveResponsePayloadArgs {
    pub success: bool,
    pub first_token: u32,
    pub num_tokens: u64,
}
impl<'a> Default for KvCacheReceiveResponsePayloadArgs {
  #[inline]
  fn default() -> Self {
    KvCacheReceiveResponsePayloadArgs {
      success: false,
      first_token: 0,
      num_tokens: 0,
    }
  }
}

pub struct KvCacheReceiveResponsePayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KvCacheReceiveResponsePayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_success(&mut self, success: bool) {
    self.fbb_.push_slot::<bool>(KvCacheReceiveResponsePayload::VT_SUCCESS, success, false);
  }
  #[inline]
  pub fn add_first_token(&mut self, first_token: u32) {
    self.fbb_.push_slot::<u32>(KvCacheReceiveResponsePayload::VT_FIRST_TOKEN, first_token, 0);
  }
  #[inline]
  pub fn add_num_tokens(&mut self, num_tokens: u64) {
    self.fbb_.push_slot::<u64>(KvCacheReceiveResponsePayload::VT_NUM_TOKENS, num_tokens, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KvCacheReceiveResponsePayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KvCacheReceiveResponsePayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<KvCacheReceiveResponsePayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for KvCacheReceiveResponsePayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("KvCacheReceiveResponsePayload");
      ds.field("success", &self.success());
      ds.field("first_token", &self.first_token());
      ds.field("num_tokens", &self.num_tokens());
      ds.finish()
  }
}
pub enum ErrorPayloadOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct ErrorPayload<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for ErrorPayload<'a> {
  type Inner = ErrorPayload<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> ErrorPayload<'a> {
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    ErrorPayload { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ErrorPayloadArgs<'args>
  ) -> ::flatbuffers::WIPOffset<ErrorPayload<'bldr>> {
    let mut builder = ErrorPayloadBuilder::new(_fbb);
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }


  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(ErrorPayload::VT_MESSAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for ErrorPayload<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct ErrorPayloadArgs<'a> {
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ErrorPayloadArgs<'a> {
  #[inline]
  fn default() -> Self {
    ErrorPayloadArgs {
      message: None,
    }
  }
}

pub struct ErrorPayloadBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ErrorPayloadBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(ErrorPayload::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ErrorPayloadBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ErrorPayloadBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<ErrorPayload<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for ErrorPayload<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("ErrorPayload");
      ds.field("message", &self.message());
      ds.finish()
  }
}
}  // pub mod ipc
}  // pub mod myelon

