// src/core/sequence.rs
use crate::utils::config::SamplingParams;
use crate::utils::image::ImageData;
use serde::{Deserialize, Serialize};
use std::fmt;
use std::time::{SystemTime, UNIX_EPOCH};

#[derive(Serialize, Deserialize, Debug, PartialEq, Eq, Clone, Copy)]
#[cfg_attr(feature = "codec-rkyv", derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize))]
pub enum SequenceStatus {
    Waiting,
    Running,
    Finished,
    Cached,        //Finished but resources not freed
    Swapped,       //kv cache swapped to CPU memory (may not finished)
    FinishSwapped, //Finished and kv cache swapped to CPU memory
}

impl fmt::Display for SequenceStatus {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let s = match self {
            SequenceStatus::Waiting => "Waiting",
            SequenceStatus::Running => "Running",
            SequenceStatus::Finished => "Finished",
            SequenceStatus::Cached => "Cached",
            SequenceStatus::Swapped => "Swapped",
            SequenceStatus::FinishSwapped => "FinishSwapped",
        };
        write!(f, "{}", s)
    }
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[cfg_attr(feature = "codec-rkyv", derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize))]
pub struct Sequence {
    pub id: usize,
    pub created_time: usize,
    pub swapped_time: Option<usize>,
    pub status: SequenceStatus,
    pub token_ids: Vec<u32>,
    pub output_ids: Vec<u32>,
    pub block_table: Vec<u32>,
    pub num_cached_tokens: usize,
    pub mamba_prefix_hash: Option<u64>,
    pub last_token: u32,
    pub block_size: usize,
    pub sampling_params: SamplingParams,
    pub pd_first_token: Option<u32>, // the first token generated by PD server
    pub images: Option<ImageData>,   // Multimodel image data
    pub is_tool_call_end: bool,
    pub hit_stop_sequence: bool,
    pub stop_sequence: Option<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
#[cfg_attr(feature = "codec-rkyv", derive(rkyv::Archive, rkyv::Serialize, rkyv::Deserialize))]
pub struct DecodeSequence {
    pub id: usize,
    pub last_token: u32,
    pub len: usize,
    pub last_block_tokens: usize,
    pub block_table_last: u32,
    pub block_tables: Vec<u32>,
    pub sampling_params: SamplingParams,
}

impl DecodeSequence {
    pub fn new(sequence: &Sequence) -> Self {
        let last_token = sequence.last_token;
        let len = sequence.len();
        let last_block_tokens = sequence.last_block_num_tokens();
        let block_table_last = *sequence.block_table.last().unwrap();
        DecodeSequence {
            id: sequence.id,
            last_token,
            len,
            last_block_tokens,
            block_table_last,
            block_tables: sequence.block_table.clone(),
            sampling_params: sequence.sampling_params.clone(),
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.len
    }
}

pub trait ToDecodeInput {
    fn last_token(&self) -> u32;
    fn len(&self) -> usize;
    fn last_block_tokens(&self) -> usize;
    fn block_table_last(&self) -> u32;
    fn block_table(&self) -> &Vec<u32>;
    fn id(&self) -> usize;
}

impl ToDecodeInput for DecodeSequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.len
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_tokens
    }

    fn block_table_last(&self) -> u32 {
        self.block_table_last
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_tables
    }

    fn id(&self) -> usize {
        self.id
    }
}

/// Read-only access surface for prefill inputs. Implemented for both
/// `&Sequence` (owned) and `&rkyv::Archived<Sequence>` (zero-copy).
///
/// RFC 0034 P2: this trait lets `prepare_prefill` consume archived
/// payload references directly from a Myelon typed lease, without
/// going through `MyelonRequest::decode → rkyv::from_bytes`.
///
/// All accessors return concrete owned scalars or borrowed slices so the
/// existing `prepare_prefill` body can use them unchanged.
#[allow(dead_code)] // used once P2 wiring lands
pub trait PrefillSeqLike {
    fn id(&self) -> usize;
    fn token_ids(&self) -> &[u32];
    fn block_table(&self) -> &[u32];
    fn num_cached_tokens(&self) -> usize;
    fn block_size(&self) -> usize;
    /// `token_ids.len()`
    fn len(&self) -> usize;
    /// `len.div_ceil(block_size)`
    fn num_blocks(&self) -> usize;
    /// `len - (num_blocks - 1) * block_size`
    fn last_block_num_tokens(&self) -> usize;
    /// `num_cached_tokens / block_size`
    fn num_cached_blocks(&self) -> usize;
    /// Mamba prefix hash if present (used by `restore_mamba_prefix_states_for_prefill`).
    fn mamba_prefix_hash(&self) -> Option<u64>;
    /// Owned copy of sampling params. Sampling params are small, so this is
    /// cheap and avoids threading lifetimes through cached_sampling state.
    fn sampling_params_owned(&self) -> SamplingParams;
    /// Image data for multimodel prefill (only inspected for first sequence).
    /// Returns `None` for archived inputs unless image plumbing lands later.
    fn images_owned(&self) -> Option<ImageData>;
}

impl PrefillSeqLike for &Sequence {
    fn id(&self) -> usize { self.id }
    fn token_ids(&self) -> &[u32] { &self.token_ids }
    fn block_table(&self) -> &[u32] { &self.block_table }
    fn num_cached_tokens(&self) -> usize { self.num_cached_tokens }
    fn block_size(&self) -> usize { self.block_size }
    fn len(&self) -> usize { self.token_ids.len() }
    fn num_blocks(&self) -> usize { Sequence::num_blocks(self) }
    fn last_block_num_tokens(&self) -> usize { Sequence::last_block_num_tokens(self) }
    fn num_cached_blocks(&self) -> usize { Sequence::num_cached_blocks(self) }
    fn mamba_prefix_hash(&self) -> Option<u64> { self.mamba_prefix_hash }
    fn sampling_params_owned(&self) -> SamplingParams { self.sampling_params.clone() }
    fn images_owned(&self) -> Option<ImageData> { self.images.clone() }
}

#[cfg(feature = "codec-rkyv")]
impl PrefillSeqLike for &rkyv::Archived<Sequence> {
    fn id(&self) -> usize {
        self.id.to_native() as usize
    }
    fn token_ids(&self) -> &[u32] {
        // ArchivedVec<u32> stores `u32_le` (rend::u32_le, #[repr(transparent)]
        // over u32 on little-endian targets). x86_64 (our only deployment) is
        // little-endian, so the byte layout of [u32_le] is identical to [u32].
        let archived: &[rkyv::rend::u32_le] = self.token_ids.as_slice();
        unsafe {
            std::slice::from_raw_parts(archived.as_ptr() as *const u32, archived.len())
        }
    }
    fn block_table(&self) -> &[u32] {
        let archived: &[rkyv::rend::u32_le] = self.block_table.as_slice();
        unsafe {
            std::slice::from_raw_parts(archived.as_ptr() as *const u32, archived.len())
        }
    }
    fn num_cached_tokens(&self) -> usize {
        self.num_cached_tokens.to_native() as usize
    }
    fn block_size(&self) -> usize {
        self.block_size.to_native() as usize
    }
    fn len(&self) -> usize {
        self.token_ids.len()
    }
    fn num_blocks(&self) -> usize {
        let len = PrefillSeqLike::len(self);
        let bs = PrefillSeqLike::block_size(self);
        len.div_ceil(bs)
    }
    fn last_block_num_tokens(&self) -> usize {
        let len = PrefillSeqLike::len(self);
        let bs = PrefillSeqLike::block_size(self);
        len - (PrefillSeqLike::num_blocks(self) - 1) * bs
    }
    fn num_cached_blocks(&self) -> usize {
        PrefillSeqLike::num_cached_tokens(self) / PrefillSeqLike::block_size(self)
    }
    fn mamba_prefix_hash(&self) -> Option<u64> {
        match self.mamba_prefix_hash.as_ref() {
            Some(h) => Some(h.to_native()),
            None => None,
        }
    }
    fn sampling_params_owned(&self) -> SamplingParams {
        // SamplingParams is small; deserialize the archived view back into an
        // owned struct via rkyv. This is the one allocation we still pay per
        // request; the main win is skipping the per-token Vec<u32> realloc.
        rkyv::deserialize::<SamplingParams, rkyv::rancor::Error>(&self.sampling_params)
            .expect("rkyv: deserialize ArchivedSamplingParams")
    }
    fn images_owned(&self) -> Option<ImageData> {
        match self.images.as_ref() {
            Some(img) => Some(
                rkyv::deserialize::<ImageData, rkyv::rancor::Error>(img)
                    .expect("rkyv: deserialize ArchivedImageData"),
            ),
            None => None,
        }
    }
}

impl ToDecodeInput for &Sequence {
    fn last_token(&self) -> u32 {
        self.last_token
    }

    fn len(&self) -> usize {
        self.tokens_len()
    }

    fn last_block_tokens(&self) -> usize {
        self.last_block_num_tokens()
    }

    fn block_table_last(&self) -> u32 {
        *self.block_table.last().unwrap()
    }

    fn block_table(&self) -> &Vec<u32> {
        &self.block_table
    }

    fn id(&self) -> usize {
        self.id
    }
}

impl Sequence {
    pub fn new(
        token_ids: Vec<u32>,
        block_size: usize,
        sampling_params: SamplingParams,
        images: &Option<ImageData>,
        image_idx: i32,
    ) -> Self {
        let images = if let Some(img) = &images {
            let mut img = img.clone(); // update the images
            img.image_idx = image_idx;
            Some(img)
        } else {
            None
        };
        Self {
            id: 0, // Will be set by scheduler
            created_time: SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .expect("Time went backwards")
                .as_millis() as usize,
            swapped_time: None,
            status: SequenceStatus::Waiting,
            token_ids: token_ids.clone(),
            output_ids: Vec::new(),
            block_table: Vec::new(),
            num_cached_tokens: 0,
            mamba_prefix_hash: None,
            sampling_params,
            block_size,
            last_token: *token_ids.last().unwrap_or(&0),
            pd_first_token: None,
            images,
            is_tool_call_end: false,
            hit_stop_sequence: false,
            stop_sequence: None,
        }
    }

    pub fn tokens_len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn len(&self) -> usize {
        self.token_ids.len()
    }

    pub fn output_len(&self) -> usize {
        self.output_ids.len()
    }

    pub fn is_finished(&self) -> bool {
        self.status == SequenceStatus::Finished
            || self.status == SequenceStatus::Cached
            || self.status == SequenceStatus::FinishSwapped
    }

    pub fn num_blocks(&self) -> usize {
        self.len().div_ceil(self.block_size)
    }

    pub fn last_block_num_tokens(&self) -> usize {
        self.len() - (self.num_blocks() - 1) * self.block_size
    }

    pub fn num_cached_blocks(&self) -> usize {
        self.num_cached_tokens / self.block_size
    }

    pub fn append_token(&mut self, token: u32) {
        self.token_ids.push(token);
        self.output_ids.push(token);
        self.last_token = token;
    }

    pub fn block(&self, index: usize) -> Vec<u32> {
        let start = index * self.block_size;
        let end = (index + 1) * self.block_size;
        self.token_ids[start..end.min(self.token_ids.len())].to_vec()
    }

    pub fn created_time(&self) -> usize {
        self.created_time
    }

    pub fn swapped_time(&self) -> Option<usize> {
        self.swapped_time
    }

    pub fn clear_block_table(&mut self) {
        self.block_table.clear();
    }
}
